### PR TITLE
docs: improve docs

### PR DESCRIPTION
**Pull request by Ghustavh97**
# Improve package documentation.

#### Notes:

- Had to use raw html headers because markdown [header ids](https://www.markdownguide.org/extended-syntax/#heading-ids) are broken and not working.

  Examples:

  ```markdown
    #### Test Header {#test-header-1}
  ```
  Outputs: 
  #### Test Header {#test-header-1} `does not generate header id and outputs it raw`

- Add CLI --help output as a QOL improvement.
- Add Table Of Contents
- Improve formatting
- Fix grammatical errors

### CODE REVIEW

**Review by jimmyandrade — APPROVED** [review]
@Ghustavh97 thanks for contributing. LGTM.

I'll just ask @evilebottnawi to take a quick look, since they have move context about the project documentation.

**Comment by jimmyandrade** [comment]
@Ghustavh97 thanks for contributing.

I'll just ask @evilebottnawi to take a quick look, since they have move context about the project documentation.

**Comment by jimmyandrade** [comment]
Merged at https://github.com/itgalaxy/webfont/commit/d426097a016c495a87f4477a21c928ba0cf30ef9.
Thank you @Ghustavh97

**Comment by Ghustavh97** [comment]
@jimmyandrade no problem, does this mean that the repo is active again?

**Comment by jimmyandrade** [comment]
@Ghustavh97 yes, it is active again!

@evilebottnawi was looking for contributors at https://github.com/itgalaxy/webfont/issues/190. As I use `webfont` in a project where I work, and I saw that it needed support, I proposed that I help him resume this project.

We are currently updating the dependencies to fix possible security vulnerabilities, in addition to integrating minor improvements. If there's anything you can help us with, it would be great to help [contributing](https://github.com/itgalaxy/webfont/blob/master/CONTRIBUTING.md)

**Comment by Ghustavh97** [comment]
@jimmyandrade awesome! I will contribute and help where ever I can. Thanks for your work!

**Pull request closed without merging**
