### PR TITLE
feat: support for processing of multiple templates via CLI and API (#158)

### LINKED ISSUE #158: Multiple templates? (Feature request)
All works great, but multiple templates would be cool

For example in the .webfontrc:
`{
...
 "template": ['html', 'scss']
...
}`

Of course not urgent, but for preview purposes, the html option would be perfect :-)

### LINKED ISSUE #279: template should accept an array
It makes no sense that **template** only accepts a string, which is either a template or a path.
Currently, it takes me 4 cycles of compiling to generate 4 nunjuck files. During each of these cycles, all the font files get re-generated.  Therefore, **template** should also accept an array of fast-globs.

### PR DESCRIPTION
**Pull request by m-jung**
- Feat: Support for processing of multiple templates via CLI and API (see [README.md](README.md)). [#158 ]
- Fixed: Where defining less font-formats using `formats` in an config-file wouldn't lead to expected result. [#199 ]
- Fixed: _"file not found"_ error if the parent output directory for fonts or templates didn't exist.

### CODE REVIEW

**Review by jimmyandrade — COMMENTED** [review]
@m-jung because of some changes we made to the main branch, there were some conflicts between your PR and our code. Could you help us to verify these issues so that we can integrate? Thank you.

**Comment by m-jung** [comment]
I've merged and updated my branch with your recent changes from master.
However, some problems remain, that i've got currently no time to tackle.
- In my branch i adopted your hash-mechanism, but rather than creating the hash based on the input, it's based on the output.
  However there seems to be an problem in the woff2 lib, which creates marginally different results (the last byte is different) for the exact same input buffer, for subsequent tests.
  I was not able to reproduce the behavior in an test that isolated the call to `wawoff2.compress()` a hundret times using the same input. Debugging on the other hand showed clearly, that different outputs results in the internal call of `compress_wrap(inputPtr, inputSize, outputPtr)`
- The Husky pre-commit hook failed with no further usefull information, so is was forced to disable it in order to commit.
  The output i've got is equal to the Travius CI build: [https://travis-ci.org/github/itgalaxy/webfont/jobs/746005346](https://travis-ci.org/github/itgalaxy/webfont/jobs/746005346)

Feel free to review.
If you are concerned about linting or prettifying i'd appreciate if you could point me in the right direction to make CI builds run successfully again.

**Comment by jimmyandrade** [comment]
The codebase has changed considerably since the last commit. Could you check it out?

**Comment by m-jung** [comment]
I'm afraid I'll have to politely decline your request.

**Pull request closed without merging**
