### PR TITLE
basic html template

### PR DESCRIPTION
**Pull request by albinotonnina**
Thanks for this, I use it in conjunction with https://github.com/itgalaxy/webpack-webfont/ 

It would be nice to generate an html page with the icons. That's what I did. I just added a basic html template.
However, it would be better to have an option to generate that html template together with the css/scss ones. I would like to implement such thing, would you be interested?

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@albinotonnina yep, let's try to do it :smile:

**Comment by evilebottnawi** [comment]
@albinotonnina btw, i near future i think deprecated `webpack-webfont` and create `webfont-loader` with support generate styles and etc staff

**Comment by evilebottnawi** [comment]
Done in 8.0.0, feel free to improve template :-1:

**Comment by albinotonnina** [comment]
I'm so sorry @evilebottnawi 
Lost the notifications on github 👎

**Comment by evilebottnawi** [comment]
@albinotonnina feel free to improve demo tempalte :+1:

**Pull request closed without merging**
