### PR TITLE
feat(ligatures, json template and template cache string): add ligature support

### LINKED ISSUE #174: feat: ligatures
Hey,

is it possible to set custom ligatures?
So that my html can look like this:
`<span class="fontclass">iconname</span>`

### LINKED ISSUE #192: Add a template cache string parameter.
example:
  src: url("./webfont.eot?1565728069335");

### PR DESCRIPTION
**Pull request by mpalpha**
#174 add ligature support

### CODE REVIEW

**Comment by mpalpha** [comment]
#192 add json built-in template and template cache string parameter

**Comment by mpalpha** [comment]
pull this project if you want to check out the changes https://github.com/mpalpha/test-fonts
use npm, and node 11+ for best results.

**Comment by guluws** [comment]
#190

**Comment by mpalpha** [comment]
> #190 Hopefully he'll read this

just use "npm i mpalpha/webfont" until then.

**Comment by Templarian** [comment]
This works with `2209` glyphs. Unfortunately anymore the TTF seems to no longer render in Chrome. The font creates [and has a much larger size]. The characters render with `&#xF08A2`, but not with the name, in this case `

Wondering if there is a limitation for the ligature table. The ligature relationships used in this way adds a lot to the file size (well at least for MDI which is 5k+ icons, but was only adding this for our desktop TTF).

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6lcar.html

Our investigation... https://github.com/Templarian/MaterialDesign-Font/issues/1

**Comment by Templarian** [comment]
Looked into this a bit further and the limit isn't the number of glyphs. It's a combination of the `codepoints + names`. `2,211 + 28,292 = 30,502`, any more characters and the TTF doesn't render using ligatures.

In my font all characters increment after `F0001`. I'm stuck trying to figure out if this a bug or a limitation of the TTF format.

**Comment by jimmyandrade** [comment]
> #190 Hopefully he'll read this

@guluws Hello, I am helping @evilebottnawi to maintain this repository. We apologize for the delay.

**Comment by jimmyandrade** [comment]
> > #190 Hopefully he'll read this
> 
> just use "npm i mpalpha/webfont" until then.

@mpalpha Does the package `mpalpha/webfont` still exist?
I believe that with the resumption of this project, we can join forces. Feel free to keep [contributing](https://github.com/itgalaxy/webfont/blob/master/CONTRIBUTING.md) here 😄

**Comment by jimmyandrade** [comment]
I accepted the PR and performed the merge with ligature and JSON support. Thank you, @mpalpha!

> Looked into this a bit further and the limit isn't the number of glyphs. It's a combination of the `codepoints + names`. `2,210 + 28,292 = 30,502`, any more characters and the TTF doesn't render using ligatures.
> 
> In my font all characters increment after `F0001`. I'm stuck trying to figure out if this a bug or a limitation of the TTF format.

@Templarian Thank you for bringing this context. We will plan a release and if, for some reason, in the new version, you find issues related to glyphs and ligatures, please feel free to share 😄

**Pull request merged**
