### PR TITLE
Add `sort` option

### PR DESCRIPTION
**Pull request by gustavobarbosacastilho**
Added: `sort` option to keep order of list items
Tests: compare the result with the expected template

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@gustavobarbosacastilho Thanks for PR, can you describe use case?

**Comment by gustavobarbosacastilho** [comment]
@evilebottnawi i want using this package with config file to improve maintenance, but i need keep order of existing font icons.

**Comment by gustavobarbosacastilho** [comment]
In standalone-test.js I added tests for these changes, but not for the CLI;

CLI does not have tests?

**Comment by evilebottnawi** [comment]
Looks good, CLI not tested right now, ping me in Monday for release

**Comment by gustavobarbosacastilho** [comment]
@evilebottnawi Okay, thank you so much, no problem.

**Comment by evilebottnawi** [comment]
@gustavobarbosacastilho done in https://github.com/itgalaxy/webfont/releases/tag/v8.2.0

**Pull request merged**
